//EMPLOYEE
###
GET http://localhost:3000/api/employee HTTP/1.1

###
GET http://localhost:3000/api/employee/asdas HTTP/1.1

###
GET http://localhost:3000/api/employee/company/643c62d7c4db6ebe214ee96e HTTP/1.1

###
POST http://localhost:3000/api/employee/ HTTP/1.1
Content-Type: application/json

{
    "name": "David",
    "surname": "Ferrer",
    "DNI": "49748069N",
    "email": "davidferrerbar02@gmail.com",
    "password": "1234",
    "company": "Employee Diary",
    "contract": 40,
    "admin": true,
    "image": "./default.jpg"
}

###
PUT http://localhost:3000/api/employee/??? HTTP/1.1
Content-Type: application/json

{
    "name": "a"
}

###
DELETE http://localhost:3000/api/employee/??? HTTP/1.1