//COMPANY
###
GET  http://localhost:3000/api/company HTTP/1.1

###
GET  http://localhost:3000/api/company/647725f298d38af1ee3f3c42 HTTP/1.1

###
POST  http://localhost:3000/api/company HTTP/1.1
Content-Type: application/json

{
    "name": "Employee Diary",
    "address": "Calle Sella nº6",
    "contractTypes": [40, 30, 20]
}

###
PUT http://localhost:3000/api/company/647725f298d38af1ee3f3c42 HTTP/1.1
Content-Type: application/json

{
    "name": "a"
}

###
DELETE http://localhost:3000/api/company/6474b9232756c00269709017 HTTP/1.1