###
GET http://localhost:3000/api/message HTTP/1.1

###
GET http://localhost:3000/api/message/643e9fe26f6f409a8a272b23 HTTP/1.1

###
GET http://localhost:3000/api/message/sender/643f8aafdca76a335933ac1f/receiver/646a4bbd568bd7c110c8bee0 HTTP/1.1

###
POST http://localhost:3000/api/message/ HTTP/1.1
Content-Type: application/json

{
    "sender": "76231428K",
    "receiver": "49748069N",
    "content": "Holaa"
}

###
PUT http://localhost:3000/api/message/643ea7283bb7935165786a9f HTTP/1.1
Content-Type: application/json

{
    "content": "quien eres'"
}

###
DELETE http://localhost:3000/api/message/643ea00d6f6f409a8a272b2b HTTP/1.1