###
GET http://localhost:3000/api/schedule HTTP/1.1

###
GET http://localhost:3000/api/schedule/643eac19ffa0bb02fe183993 HTTP/1.1

###
GET http://localhost:3000/api/schedule/employee/643f8aafdca76a335933ac1f HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNDk3NDgwNjlOIiwiaWF0IjoxNjgxODg4MDgzLCJleHAiOjE2ODE4ODgxNDN9.qWDu5Ysz97wZHoIgTai4aol3UFqnYw7v_7k0leuRQUY

###
GET http://localhost:3000/api/schedule/company/Employee-Diary HTTP/1.1

###
POST http://localhost:3000/api/schedule/daylist/49748069N HTTP/1.1
Content-Type: application/json

{
    "daylist": ["2023-06-12", "2023-06-13", "2023-06-14", "2023-06-15", "2023-06-16", "2023-06-17", "2023-06-18"]
}

###
POST http://localhost:3000/api/schedule/ HTTP/1.1
Content-Type: application/json

{
    "employee": "49748069N",
    "day": "2023-05-15",
    "hours": ["08:00-12:00"],
    "hoursCount": 8
}

###
PUT http://localhost:3000/api/schedule/643eac19ffa0bb02fe183993 HTTP/1.1
Content-Type: application/json

{
    "day": "19/04/2023"
}

###
DELETE http://localhost:3000/api/schedule/64611e96c696ec877c9f23c5 HTTP/1.1
